### ISSUE TITLE
JSON 데이터의 종류를 어떻게 나눌 것인지 의견이 필요합니다.

### ISSUE THREAD

**Issue by IforCU** [pcjo1202/airbnb-clone-front#26]
#### JSON 데이터를 만들다 보니 이런 데이터를 어떻게 할 것인지 의견이 좀 더 필요하다고 생각합니다. 
- 이유: 나중에 백엔드 작업을 할 때 프런트 엔드 수정이 일어나면 안되기 때문입니다... 

#### 제가 생각한 데이터를 나누는 방법은 다음과 같습니다.

1. **main 페이지**와 **detail 페이지**에 맞춰 2개의 JSON 데이터만 백앤드에서 만들어서 보내자.
    - 이 경우에는 main 및 detail 페이지에서 JSON을 받는 로직을 만들어서 각 컴포넌트에 뿌려야 하는 상황입니다. 
    - 이렇게 되면 JSON 데이터의 가공에 필요한 JS 코드를 main 및 detail에 작성이 필요합니다. 
    - 이미지 같은 대용량 데이터들의 처리 문제도 있습니다. (데이터를 받을 때까지의 시간...)

2. 각 **컴포넌트** 별로 JSON 받는 로직을 만들어서 백엔드도 그에 맞게 **다양한 JSON 데이터**를 보내자.
    - 이 경우에는 컴포넌트 별로 JSON 만들어야 하기 때문에 **백엔드가 데이터가 필요한 컴포넌트 만큼의 작업**(API 노가다)이 필요합니다. 
    - 또한 데이터가 날라오지 않으면 컴포넌트가 띄워지지 않는 상황이기에 스켈레톤 로딩과 같은 뼈대를 보여주는 로딩 화면으로 UX 구성이 요구 된다고 생각합니다.  즉 뼈대용 화면을 준비해야됩니다. 
    - 프런트엔드에서의 JS 로직이 상대적으로 편합니다. 
    
아니면 이 2개를 혼합해서 대용량 데이터는 컴포넌트 별로, 저용량 데이터는 한꺼번에 페이지에서 받는 방법도 있습니다. 
1 or 2번 혹은 다른 의견이 있으면 댓글 부탁드립니다.

**Comment by pcjo1202** [comment]
### 승현님께서 팀안에서 누구보다 큰 열정으로 프로젝트에 임해주신 덕분에 이런 좋은 고민을 나눌 수 있어서 감사합니다 :)

남겨주신 의견에 대해 제가 알고 있는 부분과, 생각을 한번 말씀 해드리겠습니다.

아마 전공자분들께서는 보통의 하나의 서비스를 개발하는 경우 가장 중요하고 기본이 되는 부분이 **"기획(요구사항분석)과 설계"**라고 배웠을 것이라고 생각합니다!!

그래서 개발을 시작하기전, 백엔드와 프론트엔드에서 개발하려는 서비스의 DB와 API를 설계하고 명세서를 작성하여 그것을 토대로 개발을 진행한다고 알고 있습니다.

우리가 진행하고 있는 프로젝트의 경우에는 아쉽게도 이런 설계부분이 없는 상태로 시작했기에 승현님께서 남겨주신 Data를 처리하는 부분에서 명세되어 있는 것이 없기 때문에 굉장히 애매모호해졌고, 저도 이런것에 대해 많은 생각들이 있었던 것 같습니다!

그래서 애런님께 이거 데이터를 어떻게 해야하냐고 여러번 물어봤고, DB 설계를 해야 하냐...까지 물어봤는데, 그렇게까지 하지 않아도 대충 Mock 데이터를 만들어 하라고...??? 애매하게 대답해주셨습니다 ㅋㅋㅋㅋ (어쩌면 애런에게는 어렵지 않는 부분일 수 도...)

---

저는 개인적으로 설계가 제대로 되어 명세서가 작성되어 있지 않기 때문에, **_변동사항에 있어 로직을 수정하는 것은 불가피할 것이라고 생각합니다!!_** 더군다가 프론트엔드를 거의 처음 개발하시는 입장에서는 완벽하게 할 수 없을것이기에 더욱 그래야 할 것이고요!! 

백엔드 개발을 넘어갈 때, 프론트엔드의 로직을 더이상 신경쓰고 싶지않다면, 백엔드에서 만들 API가  000이 있을 것 같다~ 정도를 이야기 하고 그것에 맞춰 간단한 JSON 데이터를 만들어 변경사항을 최소하는것이 가장 좋을 것 같다고 생각합니다! 

그런데, 이런 방법도 꽤 많은 시간과 에너지를 사용해야하기에 좋은 방법일지 아닐지 모르겠습니다..ㅎㅎ

그리고!! 프론트엔드에서 로직을 작성할때는 component 별로 구분하기 보다, "기능"에 초점을 맞춰서 개발을 합니다!! React에서의 가장 큰 최종 목표는, 렌더링을 최소화 하는 것이기 때문에 최대한 렌더링이 되지 않는 컴포넌트를 만드는 것이 중요합니다 ㅎㅎ 그래서 Context API, Redux 등을 사용하여 상태를 관리하는 것입니다. 

API요청 같은 경우는 LifeCycle 등의 문제로~~ compoent 안에서 로직을 작성하는 것은 매우 비효율적이고, 함수형 프로그래밍의 관점으로 보았을 때, 깨끗한 코드가 되지 않습니다. 

저는 그래서 api 폴더에 기능에 맞는 Class를 만들어서 로직을 작성하여 비동기 처리를 했습니다. 그리고 메모리제이션(useMemo, useCallback)과 custom Hook, React Query 등 을 사용하여 처리해주는 방식을 이용하였습니다 :)

---

# 결론적으로!!! 

- 에라이 모르겠다!!! 그냥 하나의 JSON을 다 때려박고 일단 동작하게 개발해보자!! -> **(1번)**
-> 근데, page 별로 나누는 의미는, 다시 말해  검색을 위한 _[ 숙소 List ]_와 Detail을 위한 _[숙소 상세 정보]_로 나눌 수 있을 것 같습니다! 

- 조금은 백엔드를 생각하고 개발해보자!! -> **(2번)**
-> API에 대한 설계가 간단하게라도 의논의 되고, 거기에 맞는 JSON을 만드는 것이 될 것 같습니다!! 
-> 근데...생각보다 API를 사용하는 부분의 요청 몇가지 밖에 안되어서 오래 안걸릴지도..? (설계를 많이 안해봐서 잘 몰라요 ㅎㅎ)

---

새벽 감성으로 작성한 코멘드...다 읽어주셨다면..아주 감개무량..감사합니다 ㅎㅎ하핫
